#!/bin/env sh

if [ "$#" -eq 0 ]
then
    echo "Usage: $0 <file1.tgz> ... <filen.tgz>"
    exit 1
fi

for f in ${@}
do
	if [ -f ${f} ]
	then
	    cd $(dirname ${f})
        if [ "$(command -v pigz 2>/dev/null)" = ""  ]
        then
            tar -xzvf "${file}"
        else
            tar -I pigz -xvf "${file}"
        fi
        cd - > /dev/null 
	fi
done
