#!/bin/sh

if [ "$#" -eq 0 ]
then
    echo "Usage: $0 <file1> ... <filen>"
    exit 1
fi

tzip='tar -czvf'
if [ -f "$(command -v pigz)" 2>/dev/null ]; then
  if [ "$(uname)" = "Darwin" ]; then
    if [ -x "$(command -v gtar)" ]; then
        tzip='gtar -I pigz -cvf' # Multithreaded
    else
      tzip='tar -czvf'
    fi
  else
    tzip='tar -I pigz -cvf' # Multithreaded
  fi
fi

date_suffix=""
  
# Check for the -d flag
if [ "$1" == "-d" ]; then
  date_suffix="-$(date +%Y%m%d_%H%M)"
  shift  # Remove the -d argument from the list
fi

for f in "$@"; do
  file=$(realpath "$f")

  if [ -d "$file" ]; then
    (
    cd "$(dirname "$file")"
    eval $tzip "$(basename "$file")${date_suffix}.tgz" "$(basename "$file")"
    )
  fi

  if [ -f "$file" ]; then
    (
    eval $tzip "$(basename "$file")${date_suffix}.tgz" -C "$(dirname "$file")" "$(basename "$file")"
    )
  fi
done