#!/bin/env sh

if [ "$#" -eq 0 ]
then
    echo "Usage: $0 <file1.pdf> ... <filen.pdf>"
    exit 1
fi

if [ "$(command -v inkscape)" = "" ]
then
    echo "Command inkscape not found"
    exit 1
fi

for f in ${@}
do
    while [ "$(jobs | wc -l)" -ge "$(getconf _NPROCESSORS_ONLN)" ]; do
      sleep 0.01
    done
    ([ -f "${f}" ] && inkscape -o $(echo "${f}" | sed 's/.pdf/.eps/g') ${f}) &
done
wait
